#:kivy 1.0.9

<Screen>:
    painter: painter

    PaintWidget:
        id: painter
        size: root.size

        #canvas:
        #    Color:
        #        rgb: 1, 1, 0
        #    Ellipse:
        #        pos: self.pos
        #        size: self.size

    AnchorLayout:
        anchor_x: 'left'
        anchor_y: 'top'

        Button
            size_hint: .1, .1
            text: "Clear"

            on_release: app.on_clear()
